#!/bin/bash
#
# SELF — Self-contained User Data Preserving Framework
# Copyright (C) 2021 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e

# ====== Handle arguments ===================================================
if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 program"
   exit 1
fi

PROGRAM="$1-controller"
if [ ! -e "${PROGRAM}" ] ; then
   echo >&2 "ERROR: ${PROGRAM} does not exist!"
   exit 1
fi
shift

sudo "./${PROGRAM}" $@
